trigger:
- master

pool:
  name: Default

jobs:
- job: BuildAndTest
  steps:
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'snyk'
      testType: 'code'
      failOnIssues: true
      projectName: 'MavenProjectTest'
      organization: 'sumzzgit'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
