trigger:
- master

pool:
  name: Default

jobs:
- job: BuildAndTest
  steps:
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'snyk'
      testType: 'code'
      failOnIssues: true
      projectName: 'sumzzgit/TomcatMavenApp'
      organization: '513059dd-feb7-49b0-8a40-07d8a127138a'
      additionalArguments: '--json-file-output=/home/azureuser/myagent/_work/snyk-report.json '
    

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
